# -*- coding: utf-8 -*-
r"""
train_colar_dualtrack.py
========================
Continue-train the FROZEN-LATENT colar-gsm checkpoint into a DUAL-TRACK model that emits

    [question ###(<bot>)]  [FROZEN latent chain]  ###(<eot>)  <cot> visible-CoT </cot>  \boxed{answer}

with a BOTTLENECK attention mask: the answer-generating query rows may attend ONLY to
(question + latent + <eot>), NEVER to the visible-CoT keys <cot>..</cot>.

Freeze-latent design (why this does NOT collapse the latent like Latent-SFT did)
--------------------------------------------------------------------------------
colar-gsm's latent is already causal (token-swap ~0.95).  We DO NOT retrain it.
* The latent embeds are PRE-generated by bootstrap_colar_latents.py from the frozen
  colar-gsm and spliced in here as fixed, DETACHED inputs (no gradient, no latent loss).
* latent_policy is loaded and FROZEN (and never called during training).
* The answer reads those original causal latents through the bottleneck mask, so the
  latent stays causal BY CONSTRUCTION — the only thing training changes is the
  (question+latent+<eot>) -> {visible-CoT, answer} generation.

Token mapping for CoLaR (no <think>/</think> tokens exist in CoLaR):
    <bot>  = the trailing "###" already inside the CoLaR prompt (part of the P prefix)
    <eot>  = the "###" sep_id token appended after the latent chain (as in causal_test_colar.gen)
    <cot>/</cot> = the ONLY new tokens added here (resize + init from the "###" sep embedding)

Trainable (everything else frozen):
    * the existing colar q/v LoRA adapter, at a LOW lr (--lr)   -> the CoT/answer generator
    * the two new <cot>/</cot> embedding rows (gradient-masked on the tied embedding weight)
Loss = cot_w * CE(labels_cot) + ans_w * CE(labels_answer).  NO latent / KL loss.

Loader + LatentPolicy + LoraConfig + emb_std + sep_id are copied VERBATIM from
causal_test_colar.py so loading matches the checkpoint exactly.  The 4-D bottleneck
mask geometry + _shifted_ce + <cot>/</cot> handling are copied from the Latent-SFT
template (patched_data.py / patched_modeling_stage2.py).

Env (Colab /content vs local E:/ckpts):
    COLAR_BASE COLAR_CKPT COLAR_EMB_STD(0.018) COLAR_COMPRESS(5)
Run:
    python train_colar_dualtrack.py --selftest              # pure-python: assembly + mask geometry
    COLAR_BASE=... COLAR_CKPT=.../colar_best.ckpt \
      python train_colar_dualtrack.py --data <clean.jsonl> --latents <dir> --output_dir <dir>
"""
import argparse
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
KT = HERE.parent.parent.parent

COT_OPEN = "<cot>"
COT_CLOSE = "</cot>"
QT = "Question: {} Let's think step by step:"
SPEED = "(Thinking speed: {})"


def _default(env, colab, local):
    v = os.environ.get(env)
    if v:
        return v
    return colab if os.path.isdir("/content") else local


DEF_DATA = _default("COLAR_DUALTRACK_DATA",
                    "/content/colar_dualtrack_clean.jsonl",
                    r"E:\ckpts\colar_dualtrack\colar_dualtrack_clean.jsonl")
DEF_LAT = _default("COLAR_LATENTS", "/content/colar_dualtrack_latents",
                   r"E:\ckpts\colar_dualtrack\latents")
DEF_OUT = _default("COLAR_DUALTRACK_OUT", "/content/colar_dualtrack_model",
                   r"E:\ckpts\colar_dualtrack\model")
DEF_CKPT = _default("COLAR_CKPT", "/content/colar-gsm/colar_best.ckpt",
                    r"E:\ckpts\colar-gsm\colar_best.ckpt")


# =========================================================================== #
#  PURE-PYTHON geometry (shared by --selftest and the torch training path)
# =========================================================================== #
def compute_layout(P, L, Lc, La):
    """Position layout of one dual-track sequence (single-token eot/<cot>/</cot>).

        [0, P)          question prefix ("...###" ; trailing "###" == <bot>)
        [P, P+L)        FROZEN latent embeds (spliced, no ids)
        eot_pos=P+L     "###" sep == <eot>
        cot_open_pos    <cot>
        [.. , ..+Lc)    visible CoT ids
        ccot_pos        </cot>
        answer_start    answer ids + eos
    """
    latent_start = P
    latent_end = P + L
    eot_pos = P + L
    cot_open_pos = eot_pos + 1
    cot_content_start = cot_open_pos + 1
    ccot_pos = cot_content_start + Lc
    answer_start = ccot_pos + 1
    S = answer_start + La
    return {
        "P": P, "L": L, "Lc": Lc, "La": La,
        "latent_start": latent_start, "latent_end": latent_end,
        "eot_pos": eot_pos, "cot_open_pos": cot_open_pos,
        "cot_content_start": cot_content_start, "ccot_pos": ccot_pos,
        "answer_start": answer_start, "S": S,
        # keys the answer queries may NOT attend (=[<cot> .. </cot>] inclusive)
        "cot_key_span": (cot_open_pos, answer_start),
        # bottlenecked query rows: the </cot> row (first answer producer) .. end
        "answer_query_span": (ccot_pos, S),
    }


def build_labels(lay, sep_id, cot_open_id, cot_ids, cot_close_id, answer_ids):
    """labels_cot supervises <eot>,<cot>,cot,</cot>; labels_answer supervises answer+eos.
    They partition the supervised positions (never both != -100 at one position)."""
    P, L, Lc, La = lay["P"], lay["L"], lay["Lc"], lay["La"]
    neg = [-100]
    labels_cot = (neg * P + neg * L + [sep_id] + [cot_open_id]
                  + list(cot_ids) + [cot_close_id] + neg * La)
    labels_answer = (neg * P + neg * L + neg + neg + neg * Lc + neg + list(answer_ids))
    assert len(labels_cot) == lay["S"] == len(labels_answer)
    return labels_cot, labels_answer


def py_keep_mask(S, cot_key_span, answer_query_span):
    """Pure-python bool keep-mask (True = may attend), single unpadded example:
    causal AND NOT(answer-query rows x cot-key cols)."""
    k0, k1 = cot_key_span
    q0, q1 = answer_query_span
    keep = [[j <= i for j in range(S)] for i in range(S)]      # causal
    for i in range(q0, q1):
        for j in range(k0, k1):
            keep[i][j] = False
    return keep


# =========================================================================== #
#  TORCH training (imports guarded so --selftest stays pure-python)
# =========================================================================== #
def build_bottleneck_mask_torch(B, S, pad_mask_1d, cot_key_span, answer_query_span, device):
    """4-D bool keep-mask [B,1,S,S] — geometry copied from
    patched_data.DataCollatorForDynamicPadding.build_bottleneck_mask."""
    import torch
    causal = torch.tril(torch.ones(S, S, dtype=torch.bool, device=device))
    keep = causal.unsqueeze(0).expand(B, S, S).clone()
    not_pad = pad_mask_1d.bool()
    keep = keep & not_pad.unsqueeze(1)                                   # block pad KEYS
    rows = torch.arange(S, device=device).view(1, S, 1)
    cols = torch.arange(S, device=device).view(1, 1, S)
    for b in range(B):
        k0, k1 = cot_key_span[b]
        q0, q1 = answer_query_span[b]
        block = ((rows >= q0) & (rows < q1) & (cols >= k0) & (cols < k1)).squeeze(0)
        keep[b] = keep[b] & ~block
    eye = torch.eye(S, dtype=torch.bool, device=device)
    pad_row = (~not_pad).unsqueeze(-1)                                   # force pad rows diagonal
    keep = keep | (eye.unsqueeze(0) & pad_row)
    return keep.unsqueeze(1)                                             # [B,1,S,S]


def _resize(llm, n):
    try:
        llm.resize_token_embeddings(n)
    except Exception:
        llm.base_model.model.resize_token_embeddings(n)


def build_model(base, ckpt, dev):
    """Load colar-gsm EXACTLY as causal_test_colar.py, add <cot>/</cot>, freeze all but
    the q/v LoRA + the two new embed rows.  Returns (llm, lp, tok, ids, lora_params, emb)."""
    import torch
    import torch.nn as nn
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import get_peft_model, LoraConfig, TaskType

    tok = AutoTokenizer.from_pretrained(base)
    tok.add_special_tokens({"pad_token": "[PAD]"})
    llm = AutoModelForCausalLM.from_pretrained(
        base, torch_dtype=torch.bfloat16, attn_implementation="sdpa")   # SDPA req. for 4-D mask
    llm.resize_token_embeddings(len(tok))
    llm = get_peft_model(llm, LoraConfig(task_type=TaskType.CAUSAL_LM, r=128, lora_alpha=32,
                                         target_modules=["q_proj", "v_proj"], lora_dropout=0.0))
    H = llm.config.hidden_size

    class LatentPolicy(nn.Module):
        def __init__(s, f, inter=2048):
            super().__init__()
            s.fc = nn.Sequential(nn.Linear(f, inter), nn.GELU(), nn.Linear(inter, inter), nn.LayerNorm(inter))
            s.mean = nn.Linear(inter, f); s.log_std = nn.Linear(inter, f)
        def forward(s, x, temperature=1.0):
            x = s.fc(x); return torch.distributions.Normal(s.mean(x), s.log_std(x).exp() * temperature)

    lp = LatentPolicy(H, 2048); cont = nn.Module(); cont.llm = llm; cont.latent_policy = lp
    sd = torch.load(ckpt, map_location="cpu")["state_dict"]
    miss, _ = cont.load_state_dict(sd, strict=False)
    assert not [k for k in miss if "latent_policy" in k or "lora" in k.lower()], "ckpt key mismatch"

    sep_id = tok.convert_tokens_to_ids("###")
    # ---- add the ONLY new tokens: <cot>/</cot> -----------------------------
    n_added = tok.add_special_tokens({"additional_special_tokens": [COT_OPEN, COT_CLOSE]})
    if n_added > 0:
        _resize(llm, len(tok))
    cot_open_id = tok.convert_tokens_to_ids(COT_OPEN)
    cot_close_id = tok.convert_tokens_to_ids(COT_CLOSE)
    emb = llm.get_input_embeddings()
    with torch.no_grad():                       # init new rows from the "###" boundary embedding
        emb.weight[cot_open_id] = emb.weight[sep_id].clone()
        emb.weight[cot_close_id] = emb.weight[sep_id].clone()

    llm = llm.to(dev); lp = lp.to(dev).float()

    # ---- FREEZE everything, then unfreeze ONLY (q/v LoRA) + (new embed rows) ----
    for p in llm.parameters():
        p.requires_grad_(False)
    for p in lp.parameters():                   # latent_policy frozen (and unused in training)
        p.requires_grad_(False)
    lora_params = []
    for n, p in llm.named_parameters():
        if "lora_" in n.lower():
            p.requires_grad_(True); lora_params.append(p)
    emb = llm.get_input_embeddings()
    emb.weight.requires_grad_(True)             # tied lm_head shares this weight
    new_rows = torch.tensor([cot_open_id, cot_close_id], device=emb.weight.device)

    def _emb_grad_hook(grad):                   # keep grad ONLY on the two new rows
        m = torch.zeros_like(grad); m[new_rows] = 1.0
        return grad * m
    emb.weight.register_hook(_emb_grad_hook)

    ids = {"sep_id": sep_id, "cot_open_id": cot_open_id, "cot_close_id": cot_close_id,
           "pad_id": tok.pad_token_id, "eos_id": tok.eos_token_id, "H": H}
    return llm, lp, tok, ids, lora_params, emb


def _shifted_ce(logits, labels):
    import torch.nn.functional as F
    if not (labels != -100).any():
        return logits.sum() * 0.0               # keep it in-graph, zero contribution
    sl = logits[..., :-1, :].contiguous()
    slb = labels[..., 1:].contiguous()
    return F.cross_entropy(sl.view(-1, sl.size(-1)), slb.view(-1).to(sl.device), ignore_index=-100)


def run(args):
    import random
    import torch

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    base = os.environ["COLAR_BASE"]
    ckpt = args.ckpt or os.environ.get("COLAR_CKPT") or DEF_CKPT
    COMPRESS = int(os.environ.get("COLAR_COMPRESS", "5"))
    random.seed(args.seed); torch.manual_seed(args.seed)

    llm, lp, tok, ids, lora_params, emb = build_model(base, ckpt, dev)
    sep_id, cot_open_id, cot_close_id = ids["sep_id"], ids["cot_open_id"], ids["cot_close_id"]
    pad_id, eos_id, H = ids["pad_id"], ids["eos_id"], ids["H"]
    mdtype = emb.weight.dtype

    n_train = sum(p.numel() for p in lora_params) + 2 * H
    print(f"[train] loaded; trainable = q/v LoRA ({sum(p.numel() for p in lora_params):,}) "
          f"+ 2 cot embed rows ({2*H:,}) = {n_train:,} params; latent_policy + base FROZEN", flush=True)

    if args.grad_ckpt:
        llm.gradient_checkpointing_enable()
        llm.enable_input_require_grads()

    # ---- data ---------------------------------------------------------------
    data = []
    with open(args.data, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                data.append(json.loads(line))
    if args.max_examples:
        data = data[: args.max_examples]

    def strip_think(c):
        c = c.strip()
        if c.startswith("<think>"):
            c = c[len("<think>"):]
        if c.endswith("</think>"):
            c = c[: -len("</think>")]
        return c.strip()

    # pre-tokenize the id pieces (latents load lazily from disk per step)
    for i, ex in enumerate(data):
        prefix = QT.format(str(ex["question"]).rstrip()) + SPEED.format(COMPRESS) + "###"
        ex["q_ids"] = tok(prefix, add_special_tokens=False)["input_ids"]
        ex["cot_ids"] = tok(strip_think(ex["cot"]), add_special_tokens=False)["input_ids"]
        ex["ans_ids"] = tok(ex["answer"], add_special_tokens=False)["input_ids"] + [eos_id]
        ex["_row"] = i

    def load_latent(i):
        blob = torch.load(os.path.join(args.latents, f"lat_{i:06d}.pt"), map_location="cpu")
        return blob["latent"].to(device=dev, dtype=mdtype)      # [L,H], frozen (no grad)

    # pad embeds are constants (pad = masked keys / -100 labels, never contribute to loss);
    # detach so the shared padding block is not backward'd through across steps.
    pad_emb = emb(torch.tensor([pad_id], device=dev))[0].detach()   # [H]

    def make_batch(batch_rows):
        seqs, lcs, las, cks, aqs, slens = [], [], [], [], [], []
        for i in batch_rows:
            ex = data[i]
            lat = load_latent(ex["_row"]).detach()              # FROZEN latent, no gradient
            P, L, Lc, La = len(ex["q_ids"]), lat.shape[0], len(ex["cot_ids"]), len(ex["ans_ids"])
            lay = compute_layout(P, L, Lc, La)
            q_e = emb(torch.tensor(ex["q_ids"], device=dev))
            eot_e = emb(torch.tensor([sep_id], device=dev))
            co_e = emb(torch.tensor([cot_open_id], device=dev))
            cot_e = emb(torch.tensor(ex["cot_ids"], device=dev)) if Lc else lat.new_zeros(0, H)
            cc_e = emb(torch.tensor([cot_close_id], device=dev))
            ans_e = emb(torch.tensor(ex["ans_ids"], device=dev))
            seq = torch.cat([q_e, lat, eot_e, co_e, cot_e, cc_e, ans_e], dim=0)   # [S,H]
            lc, la = build_labels(lay, sep_id, cot_open_id, ex["cot_ids"], cot_close_id, ex["ans_ids"])
            seqs.append(seq); lcs.append(lc); las.append(la)
            cks.append(lay["cot_key_span"]); aqs.append(lay["answer_query_span"]); slens.append(lay["S"])
        B, maxS = len(seqs), max(slens)
        embeds = torch.stack([
            torch.cat([s, pad_emb.view(1, H).expand(maxS - s.shape[0], H)], dim=0) for s in seqs
        ], dim=0)                                               # [B,maxS,H]
        def padlab(rows):
            t = torch.full((B, maxS), -100, dtype=torch.long, device=dev)
            for bi, r in enumerate(rows):
                t[bi, :len(r)] = torch.tensor(r, dtype=torch.long, device=dev)
            return t
        labels_cot = padlab(lcs); labels_answer = padlab(las)
        pad_mask = torch.zeros(B, maxS, dtype=torch.long, device=dev)
        for bi, s in enumerate(slens):
            pad_mask[bi, :s] = 1
        keep = build_bottleneck_mask_torch(B, maxS, pad_mask, cks, aqs, dev)   # [B,1,maxS,maxS] bool
        add = torch.zeros(keep.shape, dtype=mdtype, device=dev)
        add.masked_fill_(~keep, torch.finfo(mdtype).min)        # bool keep -> additive float
        pos = torch.arange(maxS, device=dev).unsqueeze(0).expand(B, maxS)
        return embeds, add, pos, labels_cot, labels_answer

    opt = torch.optim.AdamW([
        {"params": lora_params, "lr": args.lr, "weight_decay": 0.0},        # low-lr CoT/answer adapter
        {"params": [emb.weight], "lr": args.embed_lr, "weight_decay": 0.0},  # new cot rows (grad-masked)
    ])

    llm.train()
    rows = list(range(len(data)))
    step = 0
    os.makedirs(args.output_dir, exist_ok=True)
    loss_log = os.path.join(args.output_dir, "loss.jsonl")
    for epoch in range(args.epochs):
        random.shuffle(rows)
        opt.zero_grad()
        for bstart in range(0, len(rows), args.batch_size):
            batch_rows = rows[bstart:bstart + args.batch_size]
            embeds, add, pos, labels_cot, labels_answer = make_batch(batch_rows)
            out = llm(inputs_embeds=embeds, attention_mask=add, position_ids=pos)
            logits = out.logits
            loss_cot = _shifted_ce(logits, labels_cot)
            loss_ans = _shifted_ce(logits, labels_answer)
            loss = (args.cot_w * loss_cot + args.ans_w * loss_ans) / args.grad_accum
            loss.backward()
            step += 1
            if step % args.grad_accum == 0:
                torch.nn.utils.clip_grad_norm_([p for g in opt.param_groups for p in g["params"]], 1.0)
                opt.step(); opt.zero_grad()
            if step % args.log_every == 0:
                rec = {"epoch": epoch, "step": step,
                       "loss": float(loss.item() * args.grad_accum),
                       "loss_cot": float(loss_cot.item()), "loss_ans": float(loss_ans.item())}
                print(f"[train] e{epoch} s{step} loss={rec['loss']:.4f} "
                      f"cot={rec['loss_cot']:.4f} ans={rec['loss_ans']:.4f}", flush=True)
                with open(loss_log, "a", encoding="utf-8") as f:
                    f.write(json.dumps(rec) + "\n")
            if dev == "cuda":
                del embeds, add, logits, out
    # flush any residual grad
    if step % args.grad_accum != 0:
        torch.nn.utils.clip_grad_norm_([p for g in opt.param_groups for p in g["params"]], 1.0)
        opt.step(); opt.zero_grad()

    # ---- save: trained LoRA + the two cot embed rows + config ---------------
    llm.save_pretrained(args.output_dir)                        # updated q/v LoRA adapter
    torch.save({"cot_open_id": cot_open_id, "cot_close_id": cot_close_id, "sep_id": sep_id,
                "cot_open_row": emb.weight[cot_open_id].detach().cpu(),
                "cot_close_row": emb.weight[cot_close_id].detach().cpu()},
               os.path.join(args.output_dir, "cot_embeds.pt"))
    tok.save_pretrained(args.output_dir)
    cfg = {"base": base, "colar_ckpt": ckpt, "compress": COMPRESS,
           "emb_std": float(os.environ.get("COLAR_EMB_STD", "0.018")),
           "cot_open": COT_OPEN, "cot_close": COT_CLOSE,
           "cot_open_id": cot_open_id, "cot_close_id": cot_close_id, "sep_id": sep_id,
           "cot_w": args.cot_w, "ans_w": args.ans_w, "lr": args.lr, "embed_lr": args.embed_lr,
           "epochs": args.epochs, "batch_size": args.batch_size, "grad_accum": args.grad_accum,
           "bottleneck": "answer queries attend only [question, latent, <eot>]; <cot>..</cot> blocked",
           "frozen": "latent_policy + all base weights; only q/v LoRA + <cot>/</cot> embed rows trained",
           "n_examples": len(data)}
    with open(os.path.join(args.output_dir, "dualtrack_config.json"), "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    print(f"[train] saved LoRA + cot_embeds.pt + dualtrack_config.json -> {args.output_dir}")


# =========================================================================== #
#  --selftest : pure-python, no torch/GPU — sequence assembly + 4-D mask geometry
# =========================================================================== #
def _selftest():
    sep_id, cot_open_id, cot_close_id = 5, 100, 101       # stand-in ids
    P, L, Lc, La = 7, 4, 6, 3                             # prefix / latent / cot / answer lengths
    cot_ids = [11, 12, 13, 14, 15, 16]
    answer_ids = [20, 21, 22]
    lay = compute_layout(P, L, Lc, La)
    S = lay["S"]
    print("layout:", {k: lay[k] for k in
          ("S", "latent_start", "latent_end", "eot_pos", "cot_open_pos", "ccot_pos", "answer_start")})
    print("cot_key_span:", lay["cot_key_span"], "answer_query_span:", lay["answer_query_span"])

    # 1) lengths add up: P + L + <eot> + <cot> + Lc + </cot> + La
    assert S == P + L + 1 + 1 + Lc + 1 + La, S

    labels_cot, labels_answer = build_labels(lay, sep_id, cot_open_id, cot_ids, cot_close_id, answer_ids)
    # 2) labels partition (never both supervise a position)
    for a, b in zip(labels_cot, labels_answer):
        assert not (a != -100 and b != -100)
    # 3) latent region is unsupervised in BOTH labelings
    for p in range(lay["latent_start"], lay["latent_end"]):
        assert labels_cot[p] == -100 and labels_answer[p] == -100
    # 4) labels_cot supervises exactly [eot_pos .. answer_start): <eot>,<cot>,cot,</cot>
    assert labels_cot[lay["eot_pos"]] == sep_id
    assert labels_cot[lay["cot_open_pos"]] == cot_open_id
    assert labels_cot[lay["ccot_pos"]] == cot_close_id
    # 5) labels_answer supervises exactly the answer tail
    assert labels_answer[lay["answer_start"]:] == answer_ids

    # 6) 4-D bottleneck mask geometry (pure-python keep-mask)
    keep = py_keep_mask(S, lay["cot_key_span"], lay["answer_query_span"])
    q0, q1 = lay["answer_query_span"]
    k0, k1 = lay["cot_key_span"]
    eot_pos = lay["eot_pos"]
    # (a) causal upper triangle stays masked
    for i in range(S):
        for j in range(i + 1, S):
            assert keep[i][j] is False
    # (b) EVERY answer-query row attends ZERO into the <cot>..</cot> block
    for i in range(q0, q1):
        assert sum(1 for j in range(k0, k1) if keep[i][j]) == 0, ("leak", i)
        assert any(keep[i]), ("fully-masked row", i)                 # no NaN-risk empty row
    # (c) the FIRST answer-query row (the </cot> row) attends up to <= <eot> and no further
    first = q0
    attended = [j for j in range(S) if keep[first][j]]
    assert max(attended) == eot_pos, (max(attended), eot_pos)        # reads question+latent+<eot> only
    assert keep[first][eot_pos] and keep[first][0], "must see <eot> and question start"
    # (d) the latent keys are readable by the answer (this is WHY the latent stays causal)
    for i in range(q0, q1):
        assert all(keep[i][p] for p in range(lay["latent_start"], lay["latent_end"])), ("latent unread", i)

    print("[selftest] OK — dual-track assembly + bottleneck hold: answer reads "
          "[question, latent, <eot>] only, ZERO into <cot>..</cot>, latent always readable, "
          "labels partition, causal intact, no empty rows.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=DEF_DATA)
    ap.add_argument("--latents", default=DEF_LAT)
    ap.add_argument("--ckpt", default=None, help="overrides COLAR_CKPT")
    ap.add_argument("--output_dir", default=DEF_OUT)
    ap.add_argument("--cot_w", type=float, default=1.0)
    ap.add_argument("--ans_w", type=float, default=1.0)
    ap.add_argument("--lr", type=float, default=5e-5, help="LOW lr for the reused q/v LoRA")
    ap.add_argument("--embed_lr", type=float, default=1e-3, help="lr for the two new cot embed rows")
    ap.add_argument("--epochs", type=int, default=3)
    ap.add_argument("--batch_size", type=int, default=1)
    ap.add_argument("--grad_accum", type=int, default=8)
    ap.add_argument("--max_examples", type=int, default=0, help="0 = all")
    ap.add_argument("--log_every", type=int, default=20)
    ap.add_argument("--grad_ckpt", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        _selftest()
    else:
        run(args)
